version: '3.7'
services:
  app:
    container_name: job_portal_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mysql:${DB_PORT}
      WAIT_BEFORE_HOSTS: 15
      WAIT_SLEEP_INTERVAL: 3
    networks:
      - job-portal-stack

  mysql:
    image: mysql:5.7
    container_name: job_portal_db
    ports:
      - '3306:3306'
    environment:
      # - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - job-portal-stack

volumes:
  database_mysql:

networks:
  job-portal-stack:
    driver: bridge